"""All regulatory and assumption numbers (spec section 31). Durations in minutes unless named *_HOURS."""

MAX_DRIVING_HOURS = 11
MAX_DUTY_WINDOW_HOURS = 14
REQUIRED_REST_HOURS = 10
BREAK_AFTER_DRIVING_HOURS = 8
BREAK_DURATION_MINUTES = 30
MAX_CYCLE_HOURS = 70
CYCLE_DAYS = 8
CYCLE_RESTART_HOURS = 34
MAX_MILES_BETWEEN_FUEL = 1000
FUEL_TRIGGER_MILES = 950
FUEL_MERGE_THRESHOLD_MILES = 600
PICKUP_DURATION_MINUTES = 60
DROPOFF_DURATION_MINUTES = 60
FUEL_DURATION_MINUTES = 30
PRE_TRIP_INSPECTION_MINUTES = 15
POST_TRIP_INSPECTION_MINUTES = 15
TIME_GRID_MINUTES = 15
DAILY_REST_STATUS = "SLEEPER_BERTH"
ROUTING_PROFILE = "driving-hgv"

# Units
METERS_PER_MILE = 1609.344
MINUTES_PER_HOUR = 60
MINUTES_PER_DAY = 24 * MINUTES_PER_HOUR
EARTH_RADIUS_MILES = 3958.8
