from enum import Enum


class EventType(str, Enum):
    PRE_TRIP_INSPECTION = "PRE_TRIP_INSPECTION"
    DRIVING = "DRIVING"
    PICKUP = "PICKUP"
    DROPOFF = "DROPOFF"
    FUEL = "FUEL"
    BREAK = "BREAK"
    POST_TRIP_INSPECTION = "POST_TRIP_INSPECTION"
    DAILY_REST = "DAILY_REST"
    CYCLE_RESTART = "CYCLE_RESTART"


class DutyStatus(str, Enum):
    OFF_DUTY = "OFF_DUTY"
    SLEEPER_BERTH = "SLEEPER_BERTH"
    DRIVING = "DRIVING"
    ON_DUTY_NOT_DRIVING = "ON_DUTY_NOT_DRIVING"


_E, _D = EventType, DutyStatus
DUTY_STATUS_BY_EVENT = {
    _E.PRE_TRIP_INSPECTION: _D.ON_DUTY_NOT_DRIVING,
    _E.DRIVING: _D.DRIVING,
    _E.PICKUP: _D.ON_DUTY_NOT_DRIVING,
    _E.DROPOFF: _D.ON_DUTY_NOT_DRIVING,
    _E.FUEL: _D.ON_DUTY_NOT_DRIVING,
    _E.BREAK: _D.OFF_DUTY,
    _E.POST_TRIP_INSPECTION: _D.ON_DUTY_NOT_DRIVING,
    _E.DAILY_REST: _D.SLEEPER_BERTH,
    _E.CYCLE_RESTART: _D.OFF_DUTY,
}
